// @vitest-environment node
import { readdirSync, readFileSync, existsSync } from 'node:fs';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

import { unitCardPath, UNIT_CARD_DIR } from './cards';

/**
 * Every published lesson must have a social card on disk.
 *
 * THIS IS THE ONLY GATE THAT CAN CATCH THE REALISTIC MISTAKE. The cards are
 * generated by `pnpm icons` and committed, so writing a unit and not
 * regenerating leaves a page whose `og:image` points at a file that was never
 * made. Nothing else notices: `astro build` does not resolve `public/` paths,
 * the e2e suite checks a sample rather than all sixty, and the failure is
 * invisible from inside the site because the image is only ever fetched by
 * somebody else's server.
 *
 * A node environment rather than the suite's default jsdom — this reads the
 * repository, and nothing here needs a DOM.
 */

const UNITS_DIR = path.join(process.cwd(), 'src/content/units');

interface Unit {
  id: string;
  status: string;
}

function readUnits(): Unit[] {
  return readdirSync(UNITS_DIR)
    .filter((file) => file.endsWith('.mdx'))
    .map((file) => {
      const source = readFileSync(path.join(UNITS_DIR, file), 'utf8');
      return {
        id: file.replace(/\.mdx$/, ''),
        status: /^status:\s*(\S+)/m.exec(source)?.[1] ?? 'draft',
      };
    });
}

describe('unit social cards', () => {
  const units = readUnits();
  const published = units.filter((unit) => unit.status === 'published');

  it('finds the units to check', () => {
    // Guards the guard: if the frontmatter shape ever changes, every assertion
    // below would pass vacuously over an empty list.
    expect(published.length).toBeGreaterThan(0);
  });

  it.each(published.map((unit) => unit.id))(
    'has a card for %s',
    (id: string) => {
      const file = path.join(
        process.cwd(),
        UNIT_CARD_DIR,
        path.basename(unitCardPath(id)),
      );
      expect(
        existsSync(file),
        `no card for "${id}". Run \`pnpm icons\` and commit the result.`,
      ).toBe(true);
    },
  );

  it('has no card left behind by a deleted or unpublished unit', () => {
    // The other direction, which matters because a stale card is not an error
    // anywhere — it is just a file nobody references, quietly costing repository
    // size and implying a lesson that no longer exists.
    const cards = readdirSync(path.join(process.cwd(), UNIT_CARD_DIR))
      .filter((file) => file.endsWith('.png'))
      .map((file) => file.replace(/\.png$/, ''));

    const expected = new Set(published.map((unit) => unit.id));
    const orphans = cards.filter((id) => !expected.has(id));

    expect(orphans, `orphaned cards: ${orphans.join(', ')}`).toEqual([]);
  });
});
